# Generated by Django 5.2.17 on 2026-09-28 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de área',
                'verbose_name_plural': 'Tipos de área',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('solucion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, verbose_name='Ubicación')),
                ('usuario_nombre', models.CharField(blank=True, max_length=150, verbose_name='Usuario afectado')),
                ('usuario_correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo del usuario')),
                ('usuario_cargo', models.CharField(blank=True, max_length=150, verbose_name='Cargo / dependencia')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='core.area')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes_creados', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], max_length=15)),
                ('estado_nuevo', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], max_length=15)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='core.reporte')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EquipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_activo', models.CharField(blank=True, max_length=100, verbose_name='Código de activo')),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100, verbose_name='Número de serie')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='core.reporte')),
            ],
            options={
                'verbose_name': 'Equipo del reporte',
                'verbose_name_plural': 'Equipos del reporte',
            },
        ),
        migrations.CreateModel(
            name='ArchivoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='reportes/archivos/%Y/%m/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='core.reporte')),
            ],
            options={
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddField(
            model_name='area',
            name='tipo_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='core.tipoarea'),
        ),
        migrations.CreateModel(
            name='TipoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_tarea_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de tarea',
                'verbose_name_plural': 'Tipos de tarea',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo_tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='core.tipotarea'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edificio', models.CharField(blank=True, max_length=100)),
                ('piso', models.CharField(blank=True, max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='core.area')),
            ],
            options={
                'ordering': ['area__nombre', 'nombre'],
                'unique_together': {('nombre', 'area')},
            },
        ),
    ]
